// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idqhpsbtssifmcrpyrjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkcWhwc2J0c3NpZm1jcnB5cmpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NzM2ODcsImV4cCI6MjA3MzI0OTY4N30.4KxFMYcJ5pgxsc757qzjVWV0OeBwDSzj--FYteNeGJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});